#!/bin/bash

# Description: Link dotfiles to home directory

mkdir -p ~/.config

link_file() {
  ln -sf "$1" "$2"
  echo "Linked: $2"
}

dotfiles=("bashrc" "vimrc")

for file in "${dotfiles[@]}"; do
  link_file "$HOME/dotfiles/$file" "$HOME/.$file"
done

ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml

echo "Dotfiles Linked!"
